### ISSUE TITLE
got "no match found dcos:secrets:default" at step to grant k8s cluster secret access 

### ISSUE THREAD

**Issue by jianhuabi** [ably77/dcos-se#1]
Got an error trying to deploy a k8s cluster instances at the steps to grant k8s-cluster secret access in below. 

> dcos security org users grant kubernetes-cluster dcos:secrets:default:/kubernetes-cluster/* full **zsh: no matches found: dcos:secrets:default:/kubernetes-cluster/***

I think the reason is perhaps * is not recognized by grant command. If I modify command like in below then the command can be accepted somehow. 

> dcos security org users grant kubernetes-cluster dcos:secrets:default:/kubernetes-cluster/sa full

**Comment by jianhuabi** [comment]
> Got an error trying to deploy a k8s cluster instances at the steps to grant k8s-cluster secret access in below.
> 
> > dcos security org users grant kubernetes-cluster dcos:secrets:default:/kubernetes-cluster/* full **zsh: no matches found: dcos:secrets:default:/kubernetes-cluster/***
> 
> I think the reason is perhaps * is not recognized by grant command. If I modify command like in below then the command can be accepted somehow.
> 
> > dcos security org users grant kubernetes-cluster dcos:secrets:default:/kubernetes-cluster/sa full

Just realized it was because incompatible of zsh command shell which trying to do some magic with *. 

can be resolved via 
users grant 'kubernetes-cluster dcos:secrets:default:/kubernetes-cluster/*' full

**Comment by ably77** [comment]
Looks like this is something with zsh as mentioned, and not the DC/OS Security CLI itself. Glad you figured it out, and thanks for sharing! Will close this now.
